/* 응답 객체 모음 */
// export const ApiDocs = {
//   DslGetVersion: SuccessResponseGetVersionDto,
//   DslLogin: SuccessResponseLoginDto,
//   DslUserMe: SuccessResponseUserMeDto,
//   DslCreateUser: SuccessResponseCreateUserDto,
//   DslUpdateUser: SuccessResponseUpdateUserDto,
//   DslDeleteUser: SuccessResponseDeleteUserDto,
//   DslUpdateUserSecret: SuccessResponseUpdateUserSecretDto,
//   DslVerifyToken: SuccessResponseVerifyTokenDto,
//   DslGetProfile: SuccessResponseGetProfileDto,
//   DslCreateProfile: SuccessResponseCreateProfileDto,
//   DslUpdateProfile: SuccessResponseUpdateProfileDto,
//   DslDeleteProfile: SuccessResponseDeleteProfileDto,
//   DslGetProfileImage: SuccessResponseGetProfileImageDto,
//   DslNotFoundProfileImage: NotFoundProfileImageDto,
//   DslNotFoundUser: NotFoundResponseUserDto,
//   DslNotFoundEmail: NotFoundResponseEmailDto,
//   DslNotFoundProfile: NotFoundResponseProfileDto,
//   DslBadRequest: BadRequestResponseDto,
//   DslUnauthorized: UnauthorizedResponseDto,
// } as const;
